export const ENTITIES = {
    AgendaMedica: "AgendaMedica",
    MedioDePago: "MedioDePago",
    Sucursales: "Sucursales",
    CategoriaProd: "CategoriaProd",
    MovimientoCaja: "MovimientoCaja",
    TipoMovimiento: "TipoMovimiento",
    CierreCaja: "CierreCaja",
    Pacientes: "Pacientes",
    Tratamientos: "Tratamientos",
    Dolar: "Dolar",
    PagoDeComisiones: "PagoDeComisiones",
    Turnos: "Turnos",
    Empleado: "Empleado",
    Producto: "Producto",
    UsuarioAudit: "UsuarioAudit",
    EstadosTurnos: "EstadosTurnos",
    RecepcionPacientes: "RecepcionPacientes",
    Usuario: "Usuario",
    Medicos: "Medicos",
    Rol: "Rol",
    WhatsAppMessage: "WhatsAppMessage",
    MedicoTratamiento: "MedicoTratamiento",
    RoleComision: "RoleComision",
  } as const;
  
